# Generated by Django 2.1.5 on 2019-06-04 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20190604_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitcount',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
