# Generated by Django 2.1.5 on 2019-08-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='이름'),
        ),
    ]
