# Generated by Django 2.1.5 on 2019-08-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190819_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ref_address',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='참고항목'),
        ),
    ]
